### PR TITLE
getBy: Fix missing dependencies support

### LINKED ISSUE #338: Missing Dependent Keys
First of all, I just wanted to say well done with this addon! 

I have been playing around with this repo that last couple of days and found that there are a good amount of macros that do not have the correct dependents specified. Im not really sure if this has to do directly with ember-macro-helpers or just how this repo is parsing everything. 

### Object: `getBy`

```js
myObj: { foo: 'bar' },
someProp: 'foo',
getBy('myObj', 'someProp')
```
This only adds `myObj` and `someProp` as the dependents but it should actually be `myObj.someProp`.  

### Array Macros

All (at least the ones I've used) of the array macros do not include the necessary dependents to recompute. 

filterBy, mapBy, isAny, isEvery, etc do not include `array.@each.key` and the rest do not include `array.[]`. They only seem to include `array` and `key` if present but that is not correct. 

To get around that, you have to create intermediate properties which I think can be easily avoided if the necessary dependent keys are added. 

### Environment

Ember-CLI: 2.12
Ember: 2.12
Ember-Awesome-Macros: 0.36.0
Ember-Macro-Helpers: 0.14.1

### PR DESCRIPTION
**Pull request by mriska**
This PR introduces class-based computed support for `getBy`. 

Fixes #338

### CODE REVIEW

**Comment by mriska** [comment]
@kellyselden according to tests, this seems to solve the issue described in #338. I have not been able to test it in my own project yet since I could not get `npm link` to work for some reason.

**Comment by mriska** [comment]
@kellyselden according to tests, this seems to solve the issue described in #338. I have not been able to test it in my own project yet since I could not get `npm link` to work for some reason.

**Comment by mriska** [comment]
@kellyselden Any thoughts about this? Are there any changes you wish that I make?

File: addon/get-by.js [hunk 1]
```diff
@@ -1,8 +1,11 @@
...
+import createClassComputed from 'ember-macro-helpers/create-class-computed';
+import computed from 'ember-macro-helpers/computed';
 
-export default curriedComputed((obj, key) => {
-  if (obj && key) {
-    return get(obj, key);
+export default createClassComputed(
+  [false, true],
+  (obj, key) => {
+    return computed(`${obj}.${key}`, key, (value) => {
```
Comment (kellyselden) [inline addon/get-by.js]: `, key` can be removed, because this whole callback gets called again when key changes, creating a new computed.

**Comment by mriska** [comment]
@kellyselden Fixed according to suggestion, squashed and rebased onto current master. Thank you for a very useful addon.

**Comment by kellyselden** [comment]
Awesome fix. Thanks!

**Comment by kellyselden** [comment]
Released in https://github.com/kellyselden/ember-awesome-macros/releases/tag/v0.37.0
