### PR TITLE
Return a sorted copy from `array.sort()`

### LINKED ISSUE #249: `array.sort` breaks on DS.PromiseArray
Fails on [this line](https://github.com/kellyselden/ember-awesome-macros/blob/master/addon/array/sort.js#L41), complaining `Uncaught TypeError: array.sort is not a function`

Indeed, [`Ember.ArrayProxy`](http://emberjs.com/api/classes/Ember.ArrayProxy.html) doesn't seem to implement a `sort` method (which I guess makes sense, since it's not entirely clear what it should do)

The official `Ember.computed.sort()` [does a `slice()` to copy the array before sorting](https://github.com/emberjs/ember.js/blob/v2.11.0/packages/ember-runtime/lib/computed/reduce_computed_macros.js#L732)

I haven't delved into the `ember-awesome-macros` code far enough to see where the parameter passed into `ember-awesome-macros/array.sort()` originates, but it seems like doing the same `slice()`-to-copy should fix this issue (and probably avoid others -- right now the original array is being mutated when the sort macro is accessed, which I certainly found unexpected)

### PR DESCRIPTION
**Pull request by gabrielgrant**
Fixes #249 

Note: `sort()` currently returns `undefined` when the observed property is undefined, while [Ember's `computed.sort()` returns an empty array](https://github.com/emberjs/ember.js/blob/v2.11.0/packages/ember-runtime/lib/computed/reduce_computed_macros.js#L713). Not sure if this difference is intended, I found it a bit surprising.

At the moment, it seems [`array/-utils.normalizeArray` will accept a static default value](https://github.com/kellyselden/ember-awesome-macros/blob/master/addon/array/-utils.js#L26), but I think we'd want to use a factory function that generates default values (new `Array` objects, in this case). Changing the `normalizeArray` API seems a bit outside the scope of this PR, so I haven't actually touched this, but have added a test for the current behavior (returning `undefined`) and a skipped test for the (in my mind) expected behavior (returning an empty Array).

Happy to open another issue/PR to address this if it's something you'd like changed.

### CODE REVIEW

File: tests/unit/array/sort-test.js [hunk 1]
```diff
@@ -0,0 +1,83 @@
+import { sort } from 'ember-awesome-macros/array';
```
Comment (kellyselden) [inline tests/unit/array/sort-test.js]: Did you see the existing tests at https://github.com/kellyselden/ember-awesome-macros/blob/master/tests/integration/array/sort-test.js?

Comment (gabrielgrant) [inline tests/unit/array/sort-test.js]: Oh, no, totally missed those :man_facepalming: just saw the `length` tests in `tests/unit/array` and foolishly thought there weren't any for `sort`

Comment (gabrielgrant) [inline tests/unit/array/sort-test.js]: Would you like me to move the non-duplicate tests (the last three, I believe) into the existing integration test file? (they seemed a bit more like unit tests to me, but not sure how/where you're drawing the line?)

The composibility test was copied basically verbatim from ['length-test`](https://github.com/kellyselden/ember-awesome-macros/blob/master/tests/unit/array/length-test.js#L35), and the other two are testing the specific functionality of this patch (ie they fail without the accompanying code change)

Comment (kellyselden) [inline tests/unit/array/sort-test.js]: The line I'm using is unit tests use mocking (I verify `.sort()` was called on my mock) and the integration tests use the real implementation more along the lines of a smoke test.

Comment (gabrielgrant) [inline tests/unit/array/sort-test.js]: ok, well in that case what i've written as unit tests are in fact integration tests...but half of what's currently in the integration tests file are unit tests :P

I'll move mine over to the existing test file, and update the PR

Comment (gabrielgrant) [inline tests/unit/array/sort-test.js]: @kellyselden What are your thoughts on current behavior of returning `undefined` vs Ember.computed.sort behavior of returning `[]` when the source is `undefined`?

**Comment by gabrielgrant** [comment]
ok, moved the tests from `unit` into the existing `integration`. If this looks good, happy to rebase out the extra commits

**Comment by kellyselden** [comment]
Looks great. Feel free to squash, or I can do it via github UI.

File: tests/unit/array/sort-test.js (hunk 1 above)
Comment (kellyselden) [inline tests/unit/array/sort-test.js]: This is an issue that most the macros have. I couldn't decide what the default value is if all the params are undefined, so most return undefined. I'm seeing that lodash returns empty arrays in most cases, so maybe all the macros need this change.

**Comment by gabrielgrant** [comment]
Cool, killed the redundant test commits, should be ready to merge (squashing further if you want) afaics

**Comment by kellyselden** [comment]
Great work. Released v0.31.3.

File: tests/unit/array/sort-test.js (hunk 1 above)
Comment (kellyselden) [inline tests/unit/array/sort-test.js]: Filed an issue for this #251

**Comment by gabrielgrant** [comment]
Sweet, thanks!
